//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machine.VSTestAdapter {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Machine.VSTestAdapter.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Specifications Visual Studio Test Adapter - Discovery Complete - {0} specifications in {2} of {1} assemblies scanned..
        /// </summary>
        internal static string DISCOVERER_COMPLETE {
            get {
                return ResourceManager.GetString("DISCOVERER_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Specifications Visual Studio Test Adapter - Error while discovering specifications in assembly {0} - {1}.
        /// </summary>
        internal static string DISCOVERER_ERROR {
            get {
                return ResourceManager.GetString("DISCOVERER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Specifications Visual Studio Test Adapter - Discovering...looking in {0}.
        /// </summary>
        internal static string DISCOVERER_LOOKINGIN {
            get {
                return ResourceManager.GetString("DISCOVERER_LOOKINGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Specifications Visual Studio Test Adapter - Discovering Specifications..
        /// </summary>
        internal static string DISCOVERER_STARTING {
            get {
                return ResourceManager.GetString("DISCOVERER_STARTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Specifications Visual Studio Test Adapter - Execution Complete - {0} specifications in {1} assemblies..
        /// </summary>
        internal static string EXECUTOR_COMPLETE {
            get {
                return ResourceManager.GetString("EXECUTOR_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Specifications Visual Studio Test Adapter - Error while executing specifications in assembly {0} - {1}.
        /// </summary>
        internal static string EXECUTOR_ERROR {
            get {
                return ResourceManager.GetString("EXECUTOR_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Specifications Visual Studio Test Adapter - Executing tests in {0}.
        /// </summary>
        internal static string EXECUTOR_EXECUTINGIN {
            get {
                return ResourceManager.GetString("EXECUTOR_EXECUTINGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Specifications Visual Studio Test Adapter - Executing Specifications..
        /// </summary>
        internal static string EXECUTOR_STARTING {
            get {
                return ResourceManager.GetString("EXECUTOR_STARTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Specifications Visual Studio Test Adapter - Fatal error while executing test..
        /// </summary>
        internal static string RUNERROR {
            get {
                return ResourceManager.GetString("RUNERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BehaviorField.
        /// </summary>
        internal static string TRAIT_BEHAVIOR {
            get {
                return ResourceManager.GetString("TRAIT_BEHAVIOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassName.
        /// </summary>
        internal static string TRAIT_CLASS {
            get {
                return ResourceManager.GetString("TRAIT_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string TRAIT_SUBJECT {
            get {
                return ResourceManager.GetString("TRAIT_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Subject.
        /// </summary>
        internal static string TRAIT_SUBJECT_NOSUBJECT {
            get {
                return ResourceManager.GetString("TRAIT_SUBJECT_NOSUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string TRAIT_TAG {
            get {
                return ResourceManager.GetString("TRAIT_TAG", resourceCulture);
            }
        }
    }
}
